micronaut:
  application:
    name: my-pseudo-service
  server:
    host: 127.0.0.1
    port: 10210
    cors:
      enabled: true
    thread-selection: AUTO
    max-request-size: 2gb
    multipart:
      max-file-size: 2gb

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /api-docs/swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /api-docs/rapidoc/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /api-docs/redoc/**
  
  metrics:
    sensitive: false
    enabled: true
    tags:
      application: ${micronaut.application.name}
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

  security:
    enabled: true
    intercept-url-map:
      - pattern: /api-docs/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /prometheus/**
        http-method: GET
        access: isAnonymous()
    token:
      name-key: email
      jwt:
        signatures:
          jwks:
            keycloak-nais-test:
              url: 'https://auth.test.ssb.no/realms/ssb/protocol/openid-connect/certs'
            google:
              url: 'https://www.googleapis.com/oauth2/v3/certs'
            lab-id-north1-test:
              url: 'https://labid.lab.dapla-test-external.ssb.no/jwks'
            lab-id-north1-dev:
              url: 'https://labid.lab.dapla-dev-external.ssb.no/jwks'

  http:
    services:
      cloud-identity-service:
        url: 'https://cloudidentity.googleapis.com'
        path: '/v1'
        read-timeout: 60s

  object-storage:
    gcp:
      sid:
        bucket: ssb-dev-dapla-pseudo-service-data-export

endpoints:
  all:
    port: 10220
  info:
    enabled: true
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false
  monitor:
    enabled: true
  routes:
    enabled: true
    sensitive: false

logger:
  levels:
    io.micronaut.security: INFO
    no.ssb.dlp.pseudo.service: DEBUG

gcp:
  kms:
    credentials-path: private/gcp/sa-keys/dev-dapla-pseudo-service-test-sa-key.json
    key-uris:
      - gcp-kms://projects/staging-dapla-pseudo-6485/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1
      - gcp-kms://projects/staging-dapla-pseudo-6485/locations/europe-north1/keyRings/crypto-keyring/cryptoKeys/crypto-key

  http:
    client:
      filter:
        services:
          cloud-identity-service:
            audience: "https://www.googleapis.com/auth/cloud-identity.groups.readonly"

        credentials-path: private/gcp/sa-keys/dev-dapla-pseudo-service-test-sa-key.json

  caches:
    cloud-identity-service-cache:
      expire-after-write: 30s

sid:
  mapping.filename: "freg-snr/snr-kat-latest"
  index.filename: "sid/index"

services:
  secrets:
    impl: LOCAL
    overrides:
      pseudo-secret-ssb-common-key-1: eyJlbmNyeXB0ZWRLZXlzZXQiOiJDaVVBRUpGd00xNm0yOEQ3akFvSE03WnFyQ28vTjRCUU5FcW9McXcwelFYWmFoV0lZWmxSRXJjQkFPMGpUZmtKREFEOEtwVEdiSzNIK1gvUERYOG05cVJLREk2QU1JS3lXSTZpT3JBOWdxQmNSbzZ0TUQwSE41eXQ4VG9wUlVld0c0TXBwNTRMclI4Y0loK2hPYTU1Vkc2TnhPUmpmSjUrT0wzNllvenNCcEFSMXF1SVVoT3g3KzFtVzBLbkJsTE9CNjJsTzZhY0ZQM296QWZkQkZQMHRRbGV4ZVRFazRLbDJ4VVJkVzcxd2pIc056ZUlrbmpvbnNkcWZ2Mzd0dTcxaCs0enZjenhKWDVlQk5yQjloemIzNHVXcWpubW1QSENFdk9tdlBwMjBtNzUiLCJrZXlzZXRJbmZvIjp7InByaW1hcnlLZXlJZCI6NzY0NzIwNzQyLCJrZXlJbmZvIjpbeyJ0eXBlVXJsIjoidHlwZS5nb29nbGVhcGlzLmNvbS9nb29nbGUuY3J5cHRvLnRpbmsuQWVzU2l2S2V5Iiwic3RhdHVzIjoiRU5BQkxFRCIsImtleUlkIjo3NjQ3MjA3NDIsIm91dHB1dFByZWZpeFR5cGUiOiJUSU5LIn1dfSwia2VrVXJpIjoiZ2NwLWttczovL3Byb2plY3RzL3N0YWdpbmctZGFwbGEtcHNldWRvLTY0ODUvbG9jYXRpb25zL2V1cm9wZS1ub3J0aDEva2V5UmluZ3MvcHNldWRvLXNlcnZpY2UtY29tbW9uLWtleXJpbmcvY3J5cHRvS2V5cy9wc2V1ZG8tc2VydmljZS1jb21tb24ta2VrLTEifQ==
      pseudo-secret-ssb-common-key-2: eyJlbmNyeXB0ZWRLZXlzZXQiOiJDaVVBQ2M5SWx4RzRjTFhlZHZvcjFpZGNVZ3NxWFlPcCs2L2xDQUV5NzBTaUhrWHRlSFNFRXJVQkFJOGgxNU1CZnhodmJGS1BOMURXT2hEUGtMK2dIaUN2MGc5eVhvT3RqbFFON3VuaFQ1WnNoZ3lvcjFDZmkvWFhLWm9sTElBYnZ6US9UOTc3SWQwTGdMcDRGa2pURkp4U3VuNS9uN1QxWTlXSnFncWRHeThaWGZUZXhiNVlDVU5wbnc5M2Y3SDVjcWhsOFBmUmFNdjh2VWJ2MEd3dGlIc3BqeUtYOGh2SFlydjdXVHcwakFYd2hKZVZMOWxBOWdiSFFucXdMNS9XNEtuTlJlL2hCYkl6VEM4L05idlJ2YkhzRExxdjIvdEgxVHVmQjZjcFRnPT0iLCJrZXlzZXRJbmZvIjp7InByaW1hcnlLZXlJZCI6ODcwOTY2NTYsImtleUluZm8iOlt7InR5cGVVcmwiOiJ0eXBlLmdvb2dsZWFwaXMuY29tL2dvb2dsZS5jcnlwdG8udGluay5BZXNTaXZLZXkiLCJzdGF0dXMiOiJFTkFCTEVEIiwia2V5SWQiOjg3MDk2NjU2LCJvdXRwdXRQcmVmaXhUeXBlIjoiVElOSyJ9XX0sImtla1VyaSI6ImdjcC1rbXM6Ly9wcm9qZWN0cy9zdGFnaW5nLWRhcGxhLXBzZXVkby02NDg1L2xvY2F0aW9ucy9ldXJvcGUtbm9ydGgxL2tleVJpbmdzL3BzZXVkby1zZXJ2aWNlLWNvbW1vbi1rZXlyaW5nL2NyeXB0b0tleXMvcHNldWRvLXNlcnZpY2UtY29tbW9uLWtlazEifQ==

export:
  default-target-root: gs://ssb-dev-dapla-data-synk-ned/export

storage:
  gcs-service-account-file: private/gcp/sa-keys/dev-dapla-pseudo-service-test-sa-key.json

pseudo.secrets:
  ssb-common-key-1:
    id: pseudo-secret-ssb-common-key-1
    type: TINK_WDEK
  ssb-common-key-2:
    id: pseudo-secret-ssb-common-key-2
    type: TINK_WDEK

app-roles:
  # When using isAuthenticated() the JWT token must be signed by one of the trusted-issuers
  trusted-issuers:
    - 'https://auth.test.ssb.no/realms/ssb/protocol/openid-connect/certs'
    - 'https://labid.lab.dapla-test-external.ssb.no'
    - 'https://labid.lab.dapla-dev-external.ssb.no'
  users:
    - mic@ssb.no
  admins:
    - kons_schu@ssb.no
    - kons-lunde@ssb.no
    - mmw@ssb.no
    - mic@ssb.no
    - rpk@ssb.no
    - nvj@ssb.no

