name: Deploy alerts
run-name: Deploy alerts for Pseudo Service to test and prod

on:
  push:
    branches:
      - master
    paths:
      - ".nais/alerts.yaml"
      - ".github/workflows/alert-deploy.yml"
  workflow_dispatch:
permissions:
  id-token: write
env:
  TEAM: dapla-stat

jobs:
  test-deploy:
    name: Deploy alerts to test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        name: Retrieve AlertManager configuration
        with:
          repository: "statisticsnorway/nais-alert-config"
          path: "ext_alertconfig"
          sparse-checkout: |
            alertconfig.yaml
          sparse-checkout-cone-mode: false

      - name: Deploy to test
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: test
          RESOURCE: .nais/alerts.yaml,ext_alertconfig/alertconfig.yaml
          VAR: cluster=test,team=${{ env.TEAM }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443

  prod-deploy:
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        name: Retrieve AlertManager configuration
        with:
          repository: "statisticsnorway/nais-alert-config"
          path: "ext_alertconfig"
          sparse-checkout: |
            alertconfig.yaml
          sparse-checkout-cone-mode: false

      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: prod
          RESOURCE: .nais/alerts.yaml,ext_alertconfig/alertconfig.yaml
          VAR: cluster=prod,team=${{ env.TEAM }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
